import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#42690e',
          container: '#8fbc5a',
          fixed: '#c1f188',
          'fixed-dim': '#a6d56f',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#2b4a00',
        'on-primary-fixed': '#102000',
        'on-primary-fixed-variant': '#2e4f00',
        'inverse-primary': '#a6d56f',
        secondary: {
          DEFAULT: '#396a1c',
          container: '#b9f393',
          fixed: '#b9f393',
          'fixed-dim': '#9ed67a',
        },
        'on-secondary': '#ffffff',
        'on-secondary-container': '#3f7021',
        'on-secondary-fixed': '#092100',
        'on-secondary-fixed-variant': '#225102',
        tertiary: {
          DEFAULT: '#904181',
          container: '#eb90d6',
          fixed: '#ffd7f1',
          'fixed-dim': '#ffacea',
        },
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#6e2362',
        'on-tertiary-fixed': '#390034',
        'on-tertiary-fixed-variant': '#742968',
        surface: {
          DEFAULT: '#F9FAF7',
          dim: '#dcd9d9',
          bright: '#fcf9f8',
          'container-lowest': '#ffffff',
          'container-low': '#f6f3f2',
          container: '#f0eded',
          'container-high': '#eae7e7',
          'container-highest': '#e5e2e1',
          tint: '#42690e',
          variant: '#e5e2e1',
        },
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#43493a',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        outline: '#737969',
        'outline-variant': '#c3c9b6',
        warning: '#F59E0B',
        danger: '#EF4444',
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#fcf9f8',
        'on-background': '#1c1b1b',
        'text-secondary': '#6B7280',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'headline-xl-mobile': ['30px', { lineHeight: '38px', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      spacing: {
        'gutter': '1rem',
        'gutter-sm': '0.5rem',
        'gutter-lg': '1.5rem',
        'margin': '1rem',
        'margin-md': '1.5rem',
        'margin-lg': '2rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
      },
    },
  },
  plugins: [],
}

export default config
